services:
  postgres:
    image: postgres:16
    container_name: spacex_pg
    environment:
      POSTGRES_USER: spacex
      POSTGRES_PASSWORD: spacex
      POSTGRES_DB: spacex_hub
    ports:
      - "5432:5432"
    volumes:
      - spacex_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: spacex_redis
    ports:
      - "6379:6379"

volumes:
  spacex_pgdata:
